### ISSUE TITLE
При пополнении сберегательного счета итоговый баланс равен сумме пополнения

### ISSUE THREAD

**Issue by sergei0111** [Wassupjes/JavaQATeamDiplom#1]
# Описание
Когда баланс пополняется, то итоговый баланс равен пополнению, без учета первоначального баланса на счете.

# Локация дефекта
https://github.com/Wassupjes/JavaQATeamDiplom/blob/3426388a117ebb2ec7562b21e5b9d9ec2f65da0e/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L72-L73

# Шаги воспроизведения

1. Создать класс SavingAccountTest.
2. Создать объект класса SavingAccount с начальным балансом 2 000, мин балансом 1 000, макс балансом 10 000, ставкой 5.
3. Пополнить счет на 3 000.

***Ожидаемый результат:*** Итоговый счет равен 5 000, тест в SavingAccountTest пройден.

***Фактический результат:*** Тест в SavingAccountTest провален. Итоговый счет равен сумме пополнения 3 000.

# Тест

https://github.com/Wassupjes/JavaQATeamDiplom/blob/3426388a117ebb2ec7562b21e5b9d9ec2f65da0e/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L9

# Скриншот
![image](https://github.com/Wassupjes/JavaQATeamDiplom/assets/154595351/ebb65e8a-e63a-4dbe-b35e-67e46646fa8a)

# Окружение
* **Операционная система:** Windows 10 Pro, 64 bit
* **IDE:** Intellij IDEA 2023.3.2 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by Wassupjes** [comment]
Баг исправлен @Wassupjes .
