### ISSUE TITLE
Отсутствует исключение IllegalArgumentException, когда баланс меньше кредитного лимита .

### ISSUE THREAD

**Issue by Wassupjes** [Wassupjes/JavaQATeamDiplom#11]
# Описание
Отсутствует исключение IllegalArgumentException при значении баланса меньше значения кредитного лимита.

# Локация дефекта
https://github.com/Wassupjes/JavaQATeamDiplom/blob/bcc01babc3058dd4786d3d5226717dce2b5505e6/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19

# Шаги воспроизведения

1. Создать класс CreditAccount
2. Вызвать метод Assertions.assertThrows проверки выброса исключения вида IllegalArgumentException, со значениями баланса -1, кредитного лимита 5000, ставкой 5.
3. Запустить тест.

*Ожидаемый результат:* Тест пройден, будет выкидываться исключение: "Начальный баланс не может быть меньше кредитного лимита".

*Фактический результат:* Тест в CreditAccountTest провален. Исключение не будет выкидывается.

# Тест
https://github.com/Wassupjes/JavaQATeamDiplom/blob/77601bc5c11ddd72f470951df316012c2014630f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L62

# Скриншот
![Тест 4](https://github.com/Wassupjes/JavaQATeamDiplom/assets/155019618/69160524-8e6b-4cc6-9013-45a2c9b00d57)

* **Операционная система:** Windows 11 Домашняя для одного языка
* **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by sergei0111** [comment]
Баг исправлен @sergei0111
