### ISSUE TITLE
Отсутствует исключение IllegalArgumentException, когда кредитный лимит меньше нуля.

### ISSUE THREAD

**Issue by Wassupjes** [Wassupjes/JavaQATeamDiplom#13]
Описание
Отсутствует исключение IllegalArgumentException при значении кредитного лимита меньше нуля.

# Локация дефекта
https://github.com/Wassupjes/JavaQATeamDiplom/blob/bcc01babc3058dd4786d3d5226717dce2b5505e6/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19

# Шаги воспроизведения

1. Создать класс CreditAccount
2. Вызвать метод Assertions.assertThrows проверки выброса исключения вида IllegalArgumentException, со значениями баланса 6000, кредитного лимита -1, ставкой 5.
3. Запустить тест.

*Ожидаемый результат:* Тест пройден, будет выкидываться исключение: "Кредитный лимит не может быть меньше нуля".

*Фактический результат:* Тест в CreditAccountTest провален. Исключение не выкидывается.

# Тест
https://github.com/Wassupjes/JavaQATeamDiplom/blob/77601bc5c11ddd72f470951df316012c2014630f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L70

# Скриншот
![Тест 5](https://github.com/Wassupjes/JavaQATeamDiplom/assets/155019618/969cc78b-491d-4f17-ba43-63d8eeb2d255)

* **Операционная система:** Windows 11 Домашняя для одного языка
* **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by sergei0111** [comment]
Баг исправлен @sergei0111
