### ISSUE TITLE
Проходит покупка при значении разности баланса и суммы покупки больше кредитного лимита

### ISSUE THREAD

**Issue by Wassupjes** [Wassupjes/JavaQATeamDiplom#14]
# Описание
Проходит покупка при значении разности баланса и суммы покупки больше кредитного лимита. Не выполняется условие по превышению кредитного лимита.

# Локация дефекта
https://github.com/Wassupjes/JavaQATeamDiplom/blob/d094511bf9da85d0f9100eff81057b294a2ff872/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L45

# Шаги воспроизведения

1. Создать класс CreditAccount.
2. Создать объект класса CreditAccount с начальным балансом 1 000, лимитом кредита 5 000, ставкой 5.
3. Сумма покупки 6 001.
4. Запустить тест.

*Ожидаемый результат:* Баланс не изменился и равен 1 000, тест в CreditAccountTest пройден.

*Фактический результат:* Тест в CreditAccountTest провален. Итоговый баланс равен -5 001.

# Тест
https://github.com/Wassupjes/JavaQATeamDiplom/blob/77601bc5c11ddd72f470951df316012c2014630f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L24

# Скриншот
![Тест 6](https://github.com/Wassupjes/JavaQATeamDiplom/assets/155019618/e5f10c17-1e1a-4d4c-a823-fb3f4456e895)

* **Операционная система:** Windows 11 Домашняя для одного языка
* **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by sergei0111** [comment]
Баг исправлен @sergei0111
