### ISSUE TITLE
Итоговый баланс после покупки становится меньше, чем минимальный допустимый баланс.

### ISSUE THREAD

**Issue by sergei0111** [Wassupjes/JavaQATeamDiplom#2]
# Описание
При совершении покупки с накопительного счета итоговый баланс может быть меньше минимального баланса.

# Локация дефекта
https://github.com/Wassupjes/JavaQATeamDiplom/blob/3426388a117ebb2ec7562b21e5b9d9ec2f65da0e/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения

1. Создать класс SavingAccountTest.
2. Создать объект класса SavingAccount с начальным балансом 2 000, мин балансом 1 000, макс балансом 10 000, ставкой 5.
3. Совершить покупку на 1 000.

***Ожидаемый результат:*** Итоговый счет равен начальному балансу 2 000, тест в SavingAccountTest пройден, покупка не прошла.

***Фактический результат:*** Тест в SavingAccountTest провален. Итоговый счет равен 1 000, покупка прошла.

# Тест

https://github.com/Wassupjes/JavaQATeamDiplom/blob/3426388a117ebb2ec7562b21e5b9d9ec2f65da0e/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L22

# Скриншот
![image](https://github.com/Wassupjes/JavaQATeamDiplom/assets/154595351/ede76786-c611-4350-8a56-2b75320c6132)

# Окружение
* **Операционная система:** Windows 10 Pro, 64 bit
* **IDE:** Intellij IDEA 2023.3.2 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by Wassupjes** [comment]
Баг исправлен @Wassupjes .
