### ISSUE TITLE
При пополнении счета до максимального баланса включительно операция пополнения не проходит.

### ISSUE THREAD

**Issue by sergei0111** [Wassupjes/JavaQATeamDiplom#3]
# Описание
Когда изначальный баланс пополняется до максимального баланса включительно, операция не проходит.

# Локация дефекта
https://github.com/Wassupjes/JavaQATeamDiplom/blob/df6bf35ed15642785b60412ca663f71f10677410/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L72

# Шаги воспроизведения

1. Создать класс SavingAccountTest.
2. Создать объект класса SavingAccount с начальным балансом 2 000, мин балансом 1 000, макс балансом 10 000, ставкой 5.
3. Пополнить счет на 8 000.

***Ожидаемый результат:*** Итоговый счет равен 10 000, тест в SavingAccountTest пройден.

***Фактический результат:*** Тест в SavingAccountTest провален. Итоговый счет равен изначальному балансу.

# Тест

https://github.com/Wassupjes/JavaQATeamDiplom/blob/df6bf35ed15642785b60412ca663f71f10677410/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L33

# Скриншот
![image](https://github.com/Wassupjes/JavaQATeamDiplom/assets/154595351/4d4708dd-8093-4f37-ae4b-f76a07f5a39e)

# Окружение
* **Операционная система:** Windows 10 Pro, 64 bit
* **IDE:** Intellij IDEA 2023.3.2 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by Wassupjes** [comment]
Баг исправлен @Wassupjes .
