### ISSUE TITLE
Не выполняется оплата со сберегательного счета, если итоговый баланс равен минимально допустимому

### ISSUE THREAD

**Issue by sergei0111** [Wassupjes/JavaQATeamDiplom#4]
# Описание
Невозможно произвести оплату со сберегательного счета, когда итоговый баланс равен минимально допустимому.

# Локация дефекта
https://github.com/Wassupjes/JavaQATeamDiplom/blob/4e47fc152d59f64f33a473135dd92478c5d7d153/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения

1. Создать класс SavingAccountTest.
2. Создать тест на метод pay в тестовом классе объекта.
3. Создать объект класса SavingAccount. Выставить значения переменных initialBalance 3_000, minBalance 1_000 и amount 2_000
4. Запустить тест.

***Ожидаемый результат:*** Вывод в консоли true.

***Фактический результат:*** Вывод в консоли false.

# Тест

https://github.com/Wassupjes/JavaQATeamDiplom/blob/4e47fc152d59f64f33a473135dd92478c5d7d153/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L44

# Скриншот
![image](https://github.com/Wassupjes/JavaQATeamDiplom/assets/154595351/1a285f38-6c3b-4444-9a2a-8e495199abfd)

# Окружение
* **Операционная система:** Windows 10 Pro, 64 bit
* **IDE:** Intellij IDEA 2023.3.2 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by Wassupjes** [comment]
Баг исправлен @Wassupjes .
