### ISSUE TITLE
Не выкидывается исключение, если изначальный баланс меньше минимального баланса или больше максимального баланса.

### ISSUE THREAD

**Issue by sergei0111** [Wassupjes/JavaQATeamDiplom#5]
# Описание
Когда изначальный баланс меньше, чем минимальный баланс; или больше, чем максимальный баланс, то должно появляться исключение, что баланс некорректный.

# Локация дефекта
https://github.com/Wassupjes/JavaQATeamDiplom/blob/4e47fc152d59f64f33a473135dd92478c5d7d153/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения

1. Создать класс SavingAccountTest, создать тест shouldShowExceptionInitialBalance.
2. Вызвать метод Assertions.assertThrows проверки выброса исключения вида IllegalArgumentException.
3. В поле выброса исключения указать его вид: IllegalArgumentException.class, в поле кода, который должен выбросить это исключение создать объект: new SavingAccount(500, 1_000, 10_000, 5), начальный баланс меньше минимального баланса.
4. Вызвать метод Assertions.assertThrows проверки выброса исключения вида IllegalArgumentException.
5. В поле выброса исключения указать его вид: IllegalArgumentException.class, в поле кода, который должен выбросить это исключение создать объект: new SavingAccount(11_000, 1_000, 10_000, 5), начальный баланс больше максимального.
6. Запустить тест, посмотреть вывод на консоль.

***Ожидаемый результат:*** Выкидывается исключение: 1. "Баланс не может быть меньше " + minBalance. 2. "Баланс не может быть больше " + maxBalance.

***Фактический результат:*** Тест в SavingAccountTest провален. Исключения не выкидываются.

# Тест

https://github.com/Wassupjes/JavaQATeamDiplom/blob/4e47fc152d59f64f33a473135dd92478c5d7d153/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L55

# Скриншот
![image](https://github.com/Wassupjes/JavaQATeamDiplom/assets/154595351/3ed5f39d-ceca-451c-aad0-5422c3ed502b)

# Окружение
* **Операционная система:** Windows 10 Pro, 64 bit
* **IDE:** Intellij IDEA 2023.3.2 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by Wassupjes** [comment]
Баг исправлен @Wassupjes .
