### ISSUE TITLE
Когда минимальный баланс отрицательный, должно выкидываться исключение IllegalArgumentException. 

### ISSUE THREAD

**Issue by sergei0111** [Wassupjes/JavaQATeamDiplom#6]
# Описание
Если минимальный баланс отрицательный, должно появиться исключение о том, что минимальный баланс некорректный.

# Локация дефекта
https://github.com/Wassupjes/JavaQATeamDiplom/blob/4e47fc152d59f64f33a473135dd92478c5d7d153/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения

1. Создать класс SavingAccountTest, создать тест shouldShowExceptionMinBalance.
2. Вызвать метод Assertions.assertThrows проверки выброса исключения вида IllegalArgumentException .
3. В поле выброса исключения указать его вид: IllegalArgumentException.class, в поле кода, который должен выбросить это исключение создать объект: new SavingAccount(2_000, -1_000, 10_000, 5) с отрицательным минимальным балансом.
4. Запустить тест, посмотреть вывод на консоль.

***Ожидаемый результат:*** Тест пройден, будет выкидываться исключение: "Минимальный баланс не может быть отрицательным".

***Фактический результат:*** Тест в SavingAccountTest провален. Исключение не будет выкидываться.

# Тест

https://github.com/Wassupjes/JavaQATeamDiplom/blob/4e47fc152d59f64f33a473135dd92478c5d7d153/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L61

# Скриншот
![image](https://github.com/Wassupjes/JavaQATeamDiplom/assets/154595351/0b974677-1a0c-4bf8-bfd4-0067e1afde9e)

# Окружение
* **Операционная система:** Windows 10 Pro, 64 bit
* **IDE:** Intellij IDEA 2023.3.2 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by Wassupjes** [comment]
Баг исправлен @Wassupjes .
