### ISSUE TITLE
При оплате покупки кредитным счётом значение конечного баланса равна отрицательному значению покупки

### ISSUE THREAD

**Issue by Wassupjes** [Wassupjes/JavaQATeamDiplom#7]
# Описание
После совершения покупки конечный баланс равен отрицательному значению суммы покупки.

# Локация дефекта
https://github.com/Wassupjes/JavaQATeamDiplom/blob/2fae29ae3c4c7a807c9509710355071705fa4ec5/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L46

# Шаги воспроизведения

1. Создать класс CreditAccount
2. Создать объект класса CreditAccount с начальным балансом 1 000, лимитом кредита 5 000, ставкой 15.
3. Сумма покупки 5 999.
4. Запустить тест.

*Ожидаемый результат:* Итоговый счет равен -4 999, тест в CreditAccountTest пройден.

*Фактический результат:* Тест в CreditAccountTest провален. Итоговый счет равен -5 999.

# Тест
https://github.com/Wassupjes/JavaQATeamDiplom/blob/77601bc5c11ddd72f470951df316012c2014630f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L10

# Скриншот
![Тест 1](https://github.com/Wassupjes/JavaQATeamDiplom/assets/155019618/3919f6eb-9b40-4e33-b005-39c2788db074)

* **Операционная система:** Windows 11 Домашняя для одного языка
* **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by sergei0111** [comment]
Баг исправлен @sergei0111
