### ISSUE TITLE
При пополнении счета конечный баланс равен сумме пополнения

### ISSUE THREAD

**Issue by Wassupjes** [Wassupjes/JavaQATeamDiplom#8]
# Описание
После совершения пополнения конечный баланс равен сумме пополнения.

# Локация дефекта
https://github.com/Wassupjes/JavaQATeamDiplom/blob/2fae29ae3c4c7a807c9509710355071705fa4ec5/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L69

# Шаги воспроизведения

1. Создать класс CreditAccount
2. Создать объект класса CreditAccount с начальным балансом 1 000, лимитом кредита 5 000, ставкой 15.
3. Сумма покупки 1.
4. Запустить тест.

*Ожидаемый результат:* Итоговый счет равен 1 001, тест в CreditAccountTest пройден.

*Фактический результат:* Тест в CreditAccountTest провален. Итоговый счет равен 1.

# Тест
https://github.com/Wassupjes/JavaQATeamDiplom/blob/77601bc5c11ddd72f470951df316012c2014630f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L37

# Скриншот
![Тест 2](https://github.com/Wassupjes/JavaQATeamDiplom/assets/155019618/b5c8878f-454b-4412-ad3a-86911509aa88)

* **Операционная система:** Windows 11 Домашняя для одного языка
* **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by sergei0111** [comment]
Баг исправлен @sergei0111
