### ISSUE TITLE
Производится расчёт процентов по кредитному счёту с положительным балансом

### ISSUE THREAD

**Issue by Wassupjes** [Wassupjes/JavaQATeamDiplom#9]
# Описание
При расчёте процентов по кредиту с положительным балансом начисляются проценты к балансу.

# Локация дефекта
https://github.com/Wassupjes/JavaQATeamDiplom/blob/2fae29ae3c4c7a807c9509710355071705fa4ec5/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82

# Шаги воспроизведения

1. Создать класс CreditAccount
2. Создать объект класса CreditAccount с начальным балансом 1 000, лимитом кредита 5 000, ставкой 5.
3. Сумма покупки 1.
4. Запустить тест.

*Ожидаемый результат:* Итоговая сумма начисленных процентов по кредитному счету равен 0, тест в CreditAccountTest пройден.

*Фактический результат:* Тест в CreditAccountTest провален. Итоговая сумма начисленных процентов по кредитному счету равна 50.

# Тест
https://github.com/Wassupjes/JavaQATeamDiplom/blob/77601bc5c11ddd72f470951df316012c2014630f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L50

# Скриншот
![Тест 3](https://github.com/Wassupjes/JavaQATeamDiplom/assets/155019618/d7431ae9-a6a4-406f-af9a-e0f6ef25c630)

* **Операционная система:** Windows 11 Домашняя для одного языка
* **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by sergei0111** [comment]
Баг исправлен @sergei0111
